// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ystbkemhgbjquoomhbim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdGJrZW1oZ2JqcXVvb21oYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMDUyMjMsImV4cCI6MjA4Mzg4MTIyM30.oBXjIwmWGB_yum2WKMJvzdeOy2eHKYRJT82-xyHEwAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});